import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Button, Modal, ModalBody, ModalFooter } from "reactstrap";
import React from "react";
import Slider from "react-slick";
import { useState } from 'react';
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import Link from 'next/link'






export default function Diagnostics() {
    const [selectedService, setSelectedService] = useState(''); // Initial empty selection

    const registerUser = async event => {
        event.preventDefault()

        document.getElementById("submitbuttonform").value = "Submitting form...."

        const xhttp = new XMLHttpRequest();
        xhttp.onload = function () {
            // console.log(this.responseText.status);
        }
        xhttp.open("Post", 'https://admin.caretab.ai/wp-json/contact-form-7/v1/contact-forms/6/feedback');
        xhttp.setRequestHeader("Content-Type", "application/x-www-form-urlencoded;");
        xhttp.onreadystatechange = function () {
            if (xhttp.readyState == 4) {
                var res = JSON.parse(xhttp.responseText);
                console.log(res)
                if (res.status == "mail_sent") {
                    document.getElementById("contactForm").reset();

                    document.getElementById("showlabel").innerHTML = "Your submission has been received and we will contact you soon";

                    document.getElementById("showlabel").style.display = "block";
                    window.setTimeout(function () {
                        window.location.href = "/thankyou"
                    }, 10);

                } else {
                    document.getElementById("showlabel").innerHTML = "There was a problem with the request.";
                    document.getElementById("showlabel").style.display = "block";

                }
            }
        };
        xhttp.send("your-name=" + event.target.name.value +
            "&your-email=" + event.target.email.value +
            "&phone=" + event.target.phone.value +
            "&service=" + event.target.service.value +
            "&your-message=" + event.target.message.value)

    }

    const [modalOpen, setModalOpen] = React.useState(false);

    var settings = {
        dots: true,
        infinite: true,
        speed: 1000,
        slidesToShow: 3,
        slidesToScroll: 1,
        initialSlide: 0,
        responsive: [
            {
                breakpoint: 1024,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    infinite: true,
                    dots: true
                }
            },
            {
                breakpoint: 600,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    initialSlide: 2
                }
            },
            {
                breakpoint: 480,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1
                }
            }
        ]
    };



    return (
        <>
            <Head>
                <title>Diagnostics - Care Tab </title>
                <meta name="description" content="Generated by create next App" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="/assets/css/diagnostics.css" />
            </Head>


            <div className="hero-section" id="inquirenow">
                <div className="">
                    <div className="hero-single diagnosticsbanner bannerpad">
                        <div className="container">
                            <div className="row align-items-center">
                                <div className="col-md-12 col-lg-5">
                                    <div className="hero-content">
                                        <br></br>
                                        <h6 className="hero-sub-title wow fadeInUp" data-delay=".25s">
                                            <i><img className="brandiconw" src="/assets/img/icon/brandicon.png" alt="" /></i> Diagnostics at Home
                                        </h6>

                                        <h1 className="hero-title wow fadeInRight" data-delay=".50s">
                                            Diagnostics & Wellness <br></br>at Home
                                        </h1>

                                        <div className="hero-btn wow fadeInUp" data-delay="1s">
                                            <a href="tel:+91-7891-444-333" className="theme-btn btnc">Call for Consultation <i
                                                className="fas fa-arrow-right"></i></a>
                                        </div>
                                    </div>
                                </div>


                                <div class="col-lg-4 header-top-right"></div>
                                <div class="col-lg-3 header-top-right">
                                    <div class="bannerform align-items-center">
                                        <div class="quote-header">
                                            {/* <h4>Book an appointment with our expert</h4> */}
                                            <h4>Book Your Services!</h4>
                                        </div>
                                        <form id="contactForm" onSubmit={registerUser}>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <div class="form-icon">
                                                            <i class="far fa-user-tie"></i>
                                                            <input type="text" name="name" id="name" class="form-control" placeholder="Name" required />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <div class="form-icon">
                                                            <i class="far fa-envelope"></i>
                                                            <input type="email" name="email" id="email" class="form-control" placeholder="Email" required />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <div class="form-icon">
                                                            <i class="far fa-pencil"></i>
                                                            <input type="text" name="phone" id="phone" class="form-control" maxlength="13" minlength="10" pattern="[0-9]*" placeholder="Phone No." required />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <div class="form-icon servicesl">
                                                            <i class="far fa-pencil"></i>
                                                            <select class="form-control" value={selectedService} onChange={(e) => setSelectedService(e.target.value)} name="service" id="service" className="service" required>
                                                                <option value="">---Select Service---</option>
                                                                <option value="Doctor Consultations">Doctor Consultations</option>
                                                                <option value="Nursing Care">Nursing Care</option>
                                                                <option value="ICU Setup at Home">ICU Setup at Home</option>
                                                                <option value="Home Physiotherapy">Home Physiotherapy</option>
                                                                <option value="Diagnostics">Diagnostics</option>
                                                                <option value="Medical Equipment">Medical Equipment</option>
                                                            </select>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <div class="form-icon">
                                                            <i class="far fa-comment-lines"></i>
                                                            <textarea name="message" id="message" cols="30" rows="3" class="form-control"
                                                                placeholder="Write Your Message"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-12 mt-2">
                                                    <div className="clearfix"></div>
                                                    <p id="showlabel" style={{ display: "none" }}></p>
                                                    <input id="submitbuttonform" type="submit" className="theme-btn btnwidth" value="Get a Call!" />
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="video-area pb-100 pt-50">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6">
                            <div class="video-info wow fadeInUp" data-wow-delay=".25s">
                                <div class="site-heading mb-0">
                                    <h2 class="site-title">Accurate Tests, <span>Hassle-Free Experience</span></h2>
                                    <p className="text-justify">
                                        When a loved one requires intensive monitoring and advanced medical support, hospital stays can be stressful and overwhelming. At Care[T.A.B], we provide ICU set-ups at home, designed to deliver hospital-quality critical care in a safe, familiar environment. With advanced technology, skilled nurses, and doctor supervision, we ensure safe, continuous, and compassionate care for critically ill patients.
                                    </p>
                                </div>
                                <a href="tel:+91-7891-444-333" class="theme-btn mt-30">Call Now <i class="fas fa-arrow-right"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="video-content wow fadeInRight diagnostics1" data-wow-delay=".25s">
                                <a class="play-btn" href="#">
                                    <i class="fas fa-play"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* <!-- choose area --> */}
            <div class="choose-area pt-50 pb-50 planebg">
                <div class="container">
                    <div className="row">
                        <div className="col-sm-6">
                            <div class="site-heading mb-0">
                                <h2 class="site-title">Diagnostic <span>at Home</span></h2>

                            </div>
                        </div>
                    </div>
                    <br></br>
                    <Tabs>
                        <div class="row zindexxx">

                            <div class="col-lg-6 allboxx">
                                <div class="choose-content wow fadeInUp margint0" data-wow-delay=".25s">
                                    <div class="choose-content-wrap">
                                        <div class="row g-4 ajrow">
                                            <TabList className="lefttab">
                                                <Tab>
                                                    <div class="col-md-12">
                                                        <div class="about-item align-items-center">
                                                            <div class="icon">
                                                                <img src="/assets/img/icon/citizen.png" alt="" />
                                                            </div>
                                                            <div class="choose-item-info">
                                                                <h4 className="margobb0">Cardiac & Neurological Tests</h4>
                                                                {/* <p>Trusted hospital backing. Reliable care at home.</p> */}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </Tab>
                                                <Tab>
                                                    <div class="col-md-12">
                                                        <div class="about-item align-items-center">
                                                            <div class="icon">
                                                                <img src="/assets/img/icon/help.png" alt="" />
                                                            </div>
                                                            <div class="choose-item-info">
                                                                <h4 className="margobb0">Respiratory & Metabolic Tests</h4>
                                                                {/* <p>Doctors lead your care, not just approve it.</p> */}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </Tab>
                                                <Tab>
                                                    <div class="col-md-12">
                                                        <div class="about-item align-items-center">
                                                            <div class="icon">
                                                                <img src="/assets/img/icon/protocol.png" alt="" />
                                                            </div>
                                                            <div class="choose-item-info">
                                                                <h4 className="margobb0">Imaging & Radiology</h4>
                                                                {/* <p>We follow the same standards as hospitals.</p> */}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </Tab>
                                                
                                            </TabList>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                            

                                <TabPanel className="tabdetails">
                                    <div class="choose-content wow fadeInUp" data-wow-delay=".25s">
                                        <div class="choose-content-wrap">
                                            <div class="row g-3 row-cols-5 nursingiconbox">
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>ECG Test</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>Holter Monitoring</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>EEG Test</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                               
                                            </div>
                                        </div>
                                    </div>
                                </TabPanel>

                                <TabPanel className="tabdetails">
                                    <div class="choose-content wow fadeInUp" data-wow-delay=".25s">
                                        <div class="choose-content-wrap">
                                            <div class="row g-3 row-cols-5 nursingiconbox">
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>Pulmonary Function Test (PFT)</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>Continuous Glucose Monitoring (CGM)</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>Sleep Study</h4>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </TabPanel>

                                <TabPanel className="tabdetails">
                                    <div class="choose-content wow fadeInUp" data-wow-delay=".25s">
                                        <div class="choose-content-wrap">
                                            <div class="row g-3 row-cols-5 nursingiconbox">
                                                <div class="col-sm-4">
                                                    <div class="choose-item text-center wow fadeInUp" data-wow-delay=".25s">
                                                        <div class="nursing-icon">
                                                            <img src="/assets/img/nursingcare/icon/demo.svg" alt="" />
                                                        </div>
                                                        <div class="choose-item-info">
                                                            <h4>Home X-Ray </h4>
                                                        </div>
                                                    </div>
                                                </div>                                              
                                            </div>
                                        </div>
                                    </div>
                                </TabPanel>

                               
                            </div>

                        </div>
                    </Tabs>
                </div>
            </div>
            {/* <!-- choose area end --> */}

            <div class="living-option pt-60 pb-60">
                <div class="container">
                 
                    <div class="row g-4 slpadding ">
                        <Slider {...settings}>
                            <div class="blog-item wow fadeInUp" data-wow-delay=".25s">
                                <div class="blog-item-img">
                                    <img src="/assets/img/living/01.jpg" alt="" />
                                </div>
                                <div class="blog-item-info">
                                    <div class="blog-item-meta">
                                        <h4 class="blog-title">
                                            <a href="#">Comprehensive Health Check-Up Packages</a>
                                        </h4>
                                    </div>
                                    <p>
                                        From basic health screenings to advanced diagnostic panels, we offer customized lab packages and a wide range of specialized tests with free doctor review as per the reports.
                                    </p>
                                    <ul class="listicon">
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Basic Health Check up packages</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Advanced Health Check up packages</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Premium Health Check up packages</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Comprehensive Check up packages </p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Heart Health Check up packages</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Diabetic Health Check up packages</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="blog-item wow fadeInUp" data-wow-delay=".25s">
                                <div class="blog-item-img">
                                    <img src="/assets/img/living/02.jpg" alt="" />
                                </div>
                                <div class="blog-item-info">
                                    <div class="blog-item-meta">
                                        <h4 class="blog-title">
                                            <a href="#">Free Sample Collection from Home</a>
                                        </h4>
                                    </div>
                                    <p>
                                        Get blood, urine, and swab samples collected by trained technicians at your preferred time
                                    </p>
                                </div>
                            </div>
                            <div class="blog-item wow fadeInUp" data-wow-delay=".25s">
                                <div class="blog-item-img">
                                    <img src="/assets/img/living/03.jpg" alt="" />
                                </div>
                                <div class="blog-item-info">
                                    <div class="blog-item-meta">
                                        <h4 class="blog-title">
                                            <a href="#">Priority Radiology Test booking with Free Home Pickup</a>
                                        </h4>
                                    </div>
                                    <p>
                                        At Care[T.A.B], we ensure hassle-free access to CT, MRI, and USG scans through our trusted radiology partners.
                                    </p>
                                    <ul class="listicon">
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Free Home Pickup</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Priority Booking Without Endless Waiting. Special Discounts on CT/MRI scans booked during off-hours (5 PM – 9 AM).</p>
                                        </li>                                    
                                    </ul>
                                </div>
                            </div>
                             
                        </Slider>

                    </div>
                </div>
            </div>

            <div class="choose-area pt-70 pb-50 typesofnursing">
            <div class="container">
                <div class="row g-4 align-items-center justify-content-between wow fadeInDown" data-wow-delay=".25s">
                    <div class="col-lg-12">
                        <div class="site-heading mb-0 text-center">
                            <span class="site-title-tagline"><i class="far fa-house-chimney-heart"></i> Why Choose Us</span>
                            <h2 class="site-title">Benefits of  <span>Diagnostics & Wellness </span> at Home </h2>
                        </div>
                    </div>                   
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="choose-content wow fadeInUp" data-wow-delay=".25s">
                            <div class="choose-content-wrap">
                                <div class="row g-4">
                                    <div class="col">
                                        <div class="choose-item">
                                            <span class="count">01</span>
                                            <div class="choose-item-icon">
                                                <img src="/assets/img/icon/money.svg" alt=""/>
                                            </div>
                                            <div class="choose-item-info">
                                                <h4>Convenience</h4>
                                                <p>No travel, no waiting—tests done at home.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="choose-item">
                                            <span class="count">02</span>
                                            <div class="choose-item-icon">
                                                <img src="/assets/img/icon/team.svg" alt=""/>
                                            </div>
                                            <div class="choose-item-info">
                                                <h4>Safe & Hygienic</h4>
                                                <p>Trained phlebotomists follow strict protocols.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="choose-item">
                                            <span class="count">03</span>
                                            <div class="choose-item-icon">
                                                <img src="/assets/img/icon/care.svg" alt=""/>
                                            </div>
                                            <div class="choose-item-info">
                                                <h4>Time-Saving</h4>
                                                <p>Flexible scheduling at your convenience.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="choose-item">
                                            <span class="count">04</span>
                                            <div class="choose-item-icon">
                                                <img src="/assets/img/icon/certified.svg" alt=""/>
                                            </div>
                                            <div class="choose-item-info">
                                                <h4>Digital Reports</h4>
                                                <p>Get accurate results directly on your phone.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <div class="choose-item">
                                            <span class="count">05</span>
                                            <div class="choose-item-icon">
                                                <img src="/assets/img/icon/certified.svg" alt=""/>
                                            </div>
                                            <div class="choose-item-info">
                                                <h4>Doctor Supervision</h4>
                                                <p>Tests prescribed and reviewed by specialists.</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {/* <div class="col-lg-6">
                        <div class="choose-img wow fadeInRight" data-wow-delay=".25s">
                            <img src="/assets/img/diagnostics/dignosefront1.jpg" alt=""/>
                        </div>
                    </div> */}
                </div>
            </div>
        </div>

    
            <div class="video-area pb-50 pt-50">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-6">
                            <img className="bredius" src="/assets/img/nursingcare/whycaretabdrcon.jpg" alt="" />
                        </div>

                        <div class="col-lg-6">
                            <div class="video-info wow fadeInUp insidep" data-wow-delay=".25s">
                                <div class="site-heading mb-0">
                                    <h2 class="site-title">Why Choose Care[T.A.B]  <span>Diagnostics & Wellness Program?</span></h2>
                                    <br></br>
                                </div>
                                <div class="feature-content">
                                    <ul class="listicon">
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>NABL & NABH accredited labs with accurate & reliable results</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Trained phlebotomists & technicians for safe, hygienic testing</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Doctor-reviewed reports for correct interpretation & guidance</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Convenient scheduling at your place, your time</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Bespoke packages for preventive and wellness check-ups</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Special rate for radiology test with home pickup facility</p>
                                        </li>
                                        <li>
                                            <img src="/assets/img/icon/listicon.png" />
                                            <p>Free doctor consultation after report</p>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="cta-area">
                <div class="container">
                    <div class="cta-wrap rounded-5 w-100">
                        <div class="col-lg-7 mx-auto">
                            <div class="cta-content">
                                <h1>Skip the lab, not the test</h1>
                                <p>
                                    Don’t delay important health checks. With Care[T.A.B], trusted diagnostics come home to you.
                                </p>
                                <a href="#" class="theme-btn">Book Home Sample Collection Now!<i class="fas fa-arrow-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br></br><br></br>



        </>
    );
}
